path:/?
堆疊資訊
System.Data.SqlClient.SqlException (0x80131904): 使用者 'MicrosoftAccount\p399975@gmail.com' 的登入失敗。
   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   於 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   於 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   於 System.Data.SqlClient.SqlConnection.Open()
   於 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   於 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   於 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   於 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   於 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 ICCModule.Repository.RepositoryUtility.GetList[T](String& sErrMsg, Expression`1 filter) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\Repository\RepositoryUtility.cs: 行 30
   於 ICCModule.Repository.RepositoryUtility.GetList[T](Expression`1 filter) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\Repository\RepositoryUtility.cs: 行 49
   於 ICCModule.EntityService.Service.Service_defCode.GetList(String Kind, String NoUse) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\EntityService\Service\Service_defCode.cs: 行 59
   於 Website.Controllers.HomeController.<Index>d__0.MoveNext() 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\WebSite\Controllers\HomeController.cs: 行 59
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__11_0()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__3()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   於 System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   於 System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   於 System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
ClientConnectionId:da89bdfc-017b-4621-aeeb-9b44b5ecfd7d
Error Number:18456,State:1,Class:14   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   於 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   於 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   於 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   於 System.Data.SqlClient.SqlConnection.Open()
   於 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   於 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   於 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   於 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   於 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   於 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   於 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   於 ICCModule.Repository.RepositoryUtility.GetList[T](String& sErrMsg, Expression`1 filter) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\Repository\RepositoryUtility.cs: 行 30
   於 ICCModule.Repository.RepositoryUtility.GetList[T](Expression`1 filter) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\Repository\RepositoryUtility.cs: 行 49
   於 ICCModule.EntityService.Service.Service_defCode.GetList(String Kind, String NoUse) 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\ICCModule\EntityService\Service\Service_defCode.cs: 行 59
   於 Website.Controllers.HomeController.<Index>d__0.MoveNext() 於 C:\Users\p3999\source\repos\project1\OPPIP_2023\01_SourceCode\WebSite\Controllers\HomeController.cs: 行 59
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__11_0()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_1.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__3()
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__5(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
   於 System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   於 System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
   於 System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   於 System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)   於 IscomG2C.Utility.ErrorLog.SaveErrorLog(Exception ex, String CategoryDirName, String Message)
   於 Website.WebApiApplication.Application_Error(Object sender, EventArgs e)
   於 System.EventHandler.Invoke(Object sender, EventArgs e)
   於 System.Web.HttpApplication.RaiseOnError()
   於 System.Web.HttpApplication.RecordError(Exception error)
   於 System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error)
   於 System.Web.HttpApplication.ResumeStepsFromThreadPoolThread(Exception error)
   於 System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
   於 System.Web.Mvc.Async.SynchronizationContextUtil.<>c__DisplayClass2_0.<Sync>b__0()
   於 System.Web.Mvc.Async.SynchronizationContextUtil.<>c__DisplayClass1_0`1.<Sync>b__0(Object o)
   於 System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
   於 System.Web.Util.SynchronizationHelper.QueueSynchronous(Action action)
   於 System.Web.Mvc.Async.SynchronizationContextUtil.Sync[T](SynchronizationContext syncContext, Func`1 func)
   於 System.Web.Mvc.Async.SynchronizationContextUtil.Sync(SynchronizationContext syncContext, Action action)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.ExecuteAsynchronousCallback(Boolean timedOut)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.ExecuteAsynchronousCallback(Boolean timedOut)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.ExecuteAsynchronousCallback(Boolean timedOut)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.ExecuteAsynchronousCallback(Boolean timedOut)
   於 System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.ExecuteAsynchronousCallback(Boolean timedOut)
   於 System.Threading.Tasks.Task.Execute()
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   於 System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   於 System.Threading.ThreadPoolWorkQueue.Dispatch()

